### ISSUE TITLE
pool creation fails with error

### ISSUE THREAD

**Issue by ghost** [initlabopen/ansible-role-php-fpm-pools#7]
```
ansible 2.9.4
  config file = /home/gregf/ownCloud/dev/active/hugops-infrastructure/ansible.cfg
  configured module search path = ['/home/gregf/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.8.1 (default, Jan 22 2020, 06:38:00) [GCC 9.2.0]
```

```
listen.group': 'www-data'}) => changed=false                                                                                                  [126/9796]
  ansible_loop_var: item                                                                                                                              
  item:                                                                                                                                               
    group: gregf                                                                                                                                      
    listen: /run/php/gregf-fpm.sock                                                                                                                   
    listen.group: www-data                                                                                                                            
    listen.ower: www-data                                                                                                                             
    name: gregf                                                                                                                                       
    user: gregf                                                                                                                                       
  msg: 'AnsibleUndefinedVariable: ''dict object'' has no attribute ''iteritems'''     
```

```
- name: Configure the webserver
  hosts: www.hugops.pw
  gather_facts: True
  vars:
    php_fpm_pools:
      - name: gregf
        user: 'gregf'
        group: 'gregf'
        listen: '/run/php/gregf-fpm.sock'
        listen.ower: 'www-data'
        listen.group: 'www-data'
    php_fpm_pool_defaults:
      pm: dynamic
      pm.max_children: 150
      pm.start_servers: 20
      pm.min_spare_servers: 1
      pm.max_spare_servers: 30
      pm.status_path: /status

  roles:
    - { role: initlabopen.php-fpm-pools }
```
